version: '3.1'

services:
  # MySQL database service
  db:
    image: mysql
    container_name: db_mtym
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mtym
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80

  # Node.js API service
  api:
    image: node
    container_name: api_mtym
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ".:/home/node/app"
    environment:
      - MYSQL_HOST=db
    working_dir: /home/node/app
    command: npm run start:dev